### ISSUE TITLE
JupyterLab not working anymore since 0.13.2.

### ISSUE THREAD

**Issue by rutgervandeleur** [ml-tooling/ml-workspace#100]
First of all, thanks for the awesome workspace!

**Describe the bug:**

It seems that since version 0.13.2 JupyterLab is not longer working. It only displays a: _404 : Not FoundYou are requesting a page that does not exist!_. All other tools work as expected.

In de logs I get the following when trying to start JupyterLab:

```
[W 2021-08-24 22:26:38.352 SingleUserNotebookApp configurable:190] Config option `open_browser` not recognized by `SingleUserNotebookApp`.  Did you mean `browser`?
[W 2021-08-24 22:26:38.354 SingleUserNotebookApp configurable:190] Config option `port_retries` not recognized by `SingleUserNotebookApp`.
[W 2021-08-24 22:26:38.356 SingleUserNotebookApp configurable:190] Config option `quit_button` not recognized by `SingleUserNotebookApp`.
[W 2021-08-24 22:26:38.359 SingleUserNotebookApp configurable:190] Config option `allow_remote_access` not recognized by `SingleUserNotebookApp`.  Did you mean one of: `allow_credentials, allow_root`?
[W 2021-08-24 22:26:38.361 SingleUserNotebookApp configurable:190] Config option `trust_xheaders` not recognized by `SingleUserNotebookApp`.
[W 2021-08-24 22:26:38.362 SingleUserNotebookApp notebookapp:1534] server_extensions is deprecated, use nbserver_extensions
2021/08/24 22:26:39 [error] 134#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /user/admin/cuda13/ HTTP/1.1", upstream: "http://127.0.0.1:8090/user/admin/cuda13/", host: "172.33.1.4:8080"
[W 2021-08-24 22:26:39.889 SingleUserNotebookApp notebookapp:2034] Error loading server extension jupyter_http_over_ws
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 2027, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_http_over_ws'
/opt/conda/lib/python3.8/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
[W 2021-08-24 22:26:44.170 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.170 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.170 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.170 LabApp] 'allow_root' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.170 LabApp] 'iopub_msg_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.170 LabApp] 'iopub_data_rate_limit' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.170 LabApp] 'port_retries' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.170 LabApp] 'quit_button' was found in both NotebookApp and ServerApp. This is likely a recent change. This config will only be set in NotebookApp. Please check if you should also config these traits in ServerApp for your purpose.
[W 2021-08-24 22:26:44.170 LabApp] 'allow_remote_access' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.170 LabApp] 'disable_check_xsrf' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.170 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.170 LabApp] 'trust_xheaders' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.171 LabApp] 'trust_xheaders' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.171 LabApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.171 LabApp] 'allow_password_change' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.171 LabApp] 'allow_password_change' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2021-08-24 22:26:44.171 SingleUserNotebookApp notebookapp:2034] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 2030, in init_server_extensions
        func(self)
      File "/opt/conda/lib/python3.8/site-packages/jupyterlab/serverextension.py", line 13, in load_jupyter_server_extension
        extension.update_config(serverapp.config)
      File "/opt/conda/lib/python3.8/site-packages/nbclassic/shim.py", line 138, in update_config
        shimmed_config = self.shim_config_from_notebook_to_jupyter_server(config)
      File "/opt/conda/lib/python3.8/site-packages/nbclassic/shim.py", line 228, in shim_config_from_notebook_to_jupyter_server
        raise TraitError("Trait, {}, not found.".format(trait_name))
    traitlets.traitlets.TraitError: Trait, server_extensions, not found.
2021/08/24 22:26:44 [error] 134#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET /user/admin/cuda13/ HTTP/1.1", upstream: "http://127.0.0.1:8090/user/admin/cuda13/", host: "172.33.1.4:8080"
/opt/conda/lib/python3.8/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
  warnings.warn(warn_msg, FutureWarning)
[W 2021-08-24 22:26:44.461 SingleUserNotebookApp notebookapp:2034] Error loading server extension nbresuse
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 2027, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'nbresuse'
Patching auth into jupyter_server.base.handlers.JupyterHandler(jupyter_server.base.handlers.AuthenticatedHandler) -> JupyterHandler(jupyterhub.singleuser.mixins.HubAuthenticatedHandler, jupyter_server.base.handlers.AuthenticatedHandler)
[W 2021-08-24 22:26:47.056 SingleUserNotebookApp _version:70] jupyterhub version 1.0.0 != jupyterhub-singleuser version 1.4.1. This could cause failure to authenticate and result in redirect loops!
```

**Technical details:**

- Workspace version : 0.13.2
- Docker version : 20.10.5
- Host Machine OS (Windows/Linux/Mac): Linux (Ubuntu 20.04)
- Command used to start the workspace : From the MLHub
- Browser (Chrome/Firefox/Safari): Chrome

**Possible Fix:**

I tried to install the missing packages using pip, but did not seem to resolve anything so far.

**Comment by rutgervandeleur** [comment]
Oh I found the solution in a previous issue already! #99
