### ISSUE TITLE
Build is failing for jupyter lab theme

### ISSUE THREAD

**Issue by namanUIUC** [ml-tooling/ml-workspace#14]
when I try running `jupyter labextension install @oriolmirosa/jupyterlab_materialdarker` it installs perfectly but fails to build. Any comments on that? BTW here are the logs for that:

```
Node v11.15.0

Building jupyterlab assets (build:prod:minimize)
> node /opt/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.15.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning Pattern ["plotly-icons@latest"] is trying to unpack in the same destination "/root/.cache/yarn/v4/npm-plotly-icons-1.
3.13-31cbc2d8832df8a7ed81399ec32f03ef9043c783/node_modules/plotly-icons" as pattern ["plotly-icons@^1.1.5"]. This could resul
t in non-deterministic behavior, skipping.
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "nbdime-jupyterlab > nbdime@5.0.1" has unmet peer dependency "codemirror@^5.0.0".
warning "jupyterlab-chart-editor > react-chart-editor > draft-js-export-html@1.2.0" has unmet peer dependency "immutable@3.x.
x".
warning "jupyterlab-chart-editor > react-chart-editor > draft-js-import-html@1.4.1" has unmet peer dependency "immutable@3.x.
x".
warning "jupyterlab-chart-editor > react-chart-editor > draft-js-utils@1.4.0" has unmet peer dependency "immutable@3.x.x".
warning "jupyterlab-chart-editor > react-chart-editor > react-rangeslider@2.2.0" has incorrect peer dependency "react@^0.14.0
 || ^15.0.0".
warning "jupyterlab-chart-editor > react-chart-editor > draft-js-import-html > draft-js-import-element@1.4.0" has unmet peer
dependency "immutable@3.x.x".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 8.03s.

> node /opt/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer
yarn run v1.15.2
$ /opt/conda/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer
Done in 0.52s.

> node /opt/conda/lib/python3.6/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.15.2
$ cross-env NODE_OPTIONS=--max_old_space_size=4096 webpack --config webpack.prod.minimize.config.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/opt/conda/lib/python3.6/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/opt/conda/lib/python3.6/site-packages/jupyterlab/labextensions.py", line 105, in start
    core_config=self.core_config)

  File "/opt/conda/lib/python3.6/site-packages/jupyterlab/commands.py", line 378, in build
    command=command, clean_staging=clean_staging)

  File "/opt/conda/lib/python3.6/site-packages/jupyterlab/commands.py", line 583, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter
```

**Comment by namanUIUC** [comment]
Seems like its a docker resources issue. Able to resolve it by increasing memory from 4 GB to 8 GB.

**Comment by lukasmasuch** [comment]
Thanks for figuring this out. I'm planning to add something to the known problems section on our Readme about this issue with memory and I will do some tests on figuring out the minimum suggested memory.
