### ISSUE TITLE
Couldn't launch container after installing librairies 

### ISSUE THREAD

**Issue by ahmedbendebba1** [ml-tooling/ml-workspace#83]
Hello I have aleady run an image of ml-worskpace to create a container. I am developping a webapp in python in this container so I have installed streamlit and bigquerry-api libraires and pycharm IDE.

Now i try to start this container but it gaves me this error : 

```
Traceback (most recent call last):

File "/opt/conda/bin/jupyter-notebook", line 11, in <module>

sys.exit(main())

File "/opt/conda/lib/python3.8/site-packages/jupyter_core/application.py", line 254, in launch_instance

return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)

File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 844, in launch_instance

app.initialize(argv)

File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in inner

return method(app, *args, **kwargs)

File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 2085, in initialize

self.init_webapp()

File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 1757, in init_webapp

success = self._bind_http_server()

File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 1764, in _bind_http_server

return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()

File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 1790, in _bind_http_server_tcp

self.http_server.listen(port, self.ip)

File "/opt/conda/lib/python3.8/site-packages/tornado/tcpserver.py", line 143, in listen

sockets = bind_sockets(port, address=address)

File "/opt/conda/lib/python3.8/site-packages/tornado/netutil.py", line 168, in bind_sockets

sock.bind(sockaddr)

OSError: [Errno 99] Cannot assign requested address

2021-04-27 14:53:34,733 INFO exited: jupyter (exit status 1; not expected)

2021-04-27 14:53:35,735 INFO gave up: jupyter entered FATAL state, too many start retries too quickly

2021/04/27 14:55:01 [error] 113#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8090/", host: "localhost:8080"

2021/04/27 14:55:08 [error] 113#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8090/", host: "localhost:8080",
```

**Comment by lukasmasuch** [comment]
@ahmedbendebba1 Thanks for reporting and sorry for the issue. It seems like Jupyter is trying to use a port that is already in use by another service. Did you specify any custom Jupyter arguments/configuration? If you like, you can also share the Dockerfile with your modification, which might help to find out the issue.

**Comment by ahmedbendebba1** [comment]
@LukasMasuch Thanks for your response 
Did you specify any custom Jupyter arguments/configuration. I am useing the default minimal version of mlworkspace by running docker run -p 8080:8080 mltooling/ml-workspace-minimal:0.12.1. And after runing the image I run a container and in this container I have develeopped an app without running the dockerfile of the app in ml-workspace. But i have run 
```
pip install -r requirements.txt
```
and the requirements file is 
```google-cloud-bigquery
streamlit==0.50.2
pandas==0.23.4
altair==3.3.0
chart_studio
pyarrow
```
