### ISSUE TITLE
 404 : Not Found when accessing Jupyter Lab

### ISSUE THREAD

**Issue by Emporea** [ml-tooling/ml-workspace#99]
I get 
```
404 : Not Found

You are requesting a page that does not exist!
```
when accessing jupyter lab. 

Every other "app" is working, like vnc, the old jupyter lab and so on.

Ubuntu 18.04
Docker minimal Build
Version 0.13.2

docker logs

```
ml-workspace    | [W 19:38:29.116 NotebookApp] Error loading server extension jupyterlab
ml-workspace    |     Traceback (most recent call last):
ml-workspace    |       File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 2030, in init_server_extensions
ml-workspace    |         func(self)
ml-workspace    |       File "/opt/conda/lib/python3.8/site-packages/jupyterlab/serverextension.py", line 13, in load_jupyter_server_extension
ml-workspace    |         extension.update_config(serverapp.config)
ml-workspace    |       File "/opt/conda/lib/python3.8/site-packages/nbclassic/shim.py", line 138, in update_config
ml-workspace    |         shimmed_config = self.shim_config_from_notebook_to_jupyter_server(config)
ml-workspace    |       File "/opt/conda/lib/python3.8/site-packages/nbclassic/shim.py", line 228, in shim_config_from_notebook_to_jupyter_server
ml-workspace    |         raise TraitError("Trait, {}, not found.".format(trait_name))
ml-workspace    |     traitlets.traitlets.TraitError: Trait, server_extensions, not found.
ml-workspace    | [W 19:38:29.118 NotebookApp] Error loading server extension jupyterlab_git
ml-workspace    |     Traceback (most recent call last):
ml-workspace    |       File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 2027, in init_server_extensions
ml-workspace    |         mod = importlib.import_module(modulename)
ml-workspace    |       File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
ml-workspace    |         return _bootstrap._gcd_import(name[level:], package, level)
ml-workspace    |       File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
ml-workspace    |       File "<frozen importlib._bootstrap>", line 991, in _find_and_load
ml-workspace    |       File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ml-workspace    |     ModuleNotFoundError: No module named 'jupyterlab_git'
ml-workspace    | /opt/conda/lib/python3.8/site-packages/jupyter_server/transutils.py:13: FutureWarning: The alias `_()` will be deprecated. Use `_i18n()` instead.
ml-workspace    |   warnings.warn(warn_msg, FutureWarning)
ml-workspace    | [W 19:38:29.369 NotebookApp] Error loading server extension nbresuse
ml-workspace    |     Traceback (most recent call last):
ml-workspace    |       File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 2027, in init_server_extensions
ml-workspace    |         mod = importlib.import_module(modulename)
ml-workspace    |       File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
ml-workspace    |         return _bootstrap._gcd_import(name[level:], package, level)
ml-workspace    |       File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
ml-workspace    |       File "<frozen importlib._bootstrap>", line 991, in _find_and_load
ml-workspace    |       File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ml-workspace    |     ModuleNotFoundError: No module named 'nbresuse'
ml-workspace    | [W 19:38:44.773 NotebookApp] 404 GET /lab (127.0.0.1) 7.340000ms referer=None
```

**Comment by lukasmasuch** [comment]
@Emporea Thanks for submitting the bug :) Did you update from a previous version of the workspace? There seems to be a problem involving the configuration backup functionality. Deleting the `/workspace/.workspace/backup/.jupyter` and `/workspace/.workspace/backup/.config` folders within the workspace and, subsequently, restarting the new workspace might solve this problem.

**Comment by Emporea** [comment]
Yeah I came from 0.12.x. But you were right, deleting the .workspace folder and recreating the docker container fixed the problem. Forgot about these persistent config files inside the workspace. 

Thank you.
